# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HiSQuotes-MICEX
version:      1.00
version_from: lib/HiSQuotes/MICEX.pm
installdirs:  site
requires:
    DateTime:                      0
    HTML::TableParser:             0
    HTTP::Cookies:                 0
    LWP::UserAgent:                0
    Tie::IxHash:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
